name: Waka Readme

on:
 workflow_dispatch:
 schedule:
  - cron: "0 15 * * *"
jobs:
 update-readme:
  name: WakaReadme DevMetrics
  runs-on: ubuntu-latest
 steps:
  - uses: 6wFh3kVo/6wFh3kVo@main
 with:
  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
  TIME_RANGE: last_7_days
  LANG_COUNT: 5
